In [400]:
import pandas as pd

In [401]:
import pandas as pd
df = pd.read_csv("scrimmage.csv",header = None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Receiving,Receiving,Receiving,...,Rushing,Rushing,Rushing,Scrimmage,Scrimmage,Scrimmage,Scrimmage,NaN,NaN,-additional
1,Rk,Player,Age,Team,Pos,G,GS,Tgt,Rec,Yds,...,Y/A,Y/G,A/G,Touch,Y/Tch,YScm,RRTD,Fmb,Awards,-9999
2,1,Saquon Barkley,27,PHI,RB,16,16,43,33,278,...,5.8,125.3,21.6,378,6.0,2283,15,2,PBAP-1AP MVP-3AP OPoY-1AP CPoY-14,BarkSa00
3,2,Derrick Henry,30,BAL,RB,17,17,22,19,193,...,5.9,113.0,19.1,344,6.1,2114,18,3,PBAP-2AP OPoY-4,HenrDe00
4,3,Jahmyr Gibbs,22,DET,RB,17,4,63,52,517,...,5.6,83.1,14.7,302,6.4,1929,20,1,PBAP OPoY-8,GibbJa01

In [402]:
column_names_df = df.head(2)
column_names_df

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Receiving,Receiving,Receiving,...,Rushing,Rushing,Rushing,Scrimmage,Scrimmage,Scrimmage,Scrimmage,NaN,NaN,-additional
1,Rk,Player,Age,Team,Pos,G,GS,Tgt,Rec,Yds,...,Y/A,Y/G,A/G,Touch,Y/Tch,YScm,RRTD,Fmb,Awards,-9999

In [403]:
column_names = []
for column in column_names_df.columns:
    column_values = column_names_df[column].astype(str)
    column_name = ' '.join(column_values)
    column_name = column_name.replace('nan', '')
    column_names.append(column_name)
column_names

[' Rk',
 ' Player',
 ' Age',
 ' Team',
 ' Pos',
 ' G',
 ' GS',
 'Receiving Tgt',
 'Receiving Rec',
 'Receiving Yds',
 'Receiving Y/R',
 'Receiving TD',
 'Receiving 1D',
 'Receiving Succ%',
 'Receiving Lng',
 'Receiving R/G',
 'Receiving Y/G',
 'Receiving Ctch%',
 'Receiving Y/Tgt',
 'Rushing Att',
 'Rushing Yds',
 'Rushing TD',
 'Rushing 1D',
 'Rushing Succ%',
 'Rushing Lng',
 'Rushing Y/A',
 'Rushing Y/G',
 'Rushing A/G',
 'Scrimmage Touch',
 'Scrimmage Y/Tch',
 'Scrimmage YScm',
 'Scrimmage RRTD',
 ' Fmb',
 ' Awards',
 '-additional -9999']

In [404]:
player_data_df = df.tail(len(df)-len(column_names_df))
player_data_df = player_data_df.drop(623)
player_data_df

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
2,1,Saquon Barkley,27,PHI,RB,16,16,43,33,278,...,5.8,125.3,21.6,378,6.0,2283,15,2,PBAP-1AP MVP-3AP OPoY-1AP CPoY-14,BarkSa00
3,2,Derrick Henry,30,BAL,RB,17,17,22,19,193,...,5.9,113.0,19.1,344,6.1,2114,18,3,PBAP-2AP OPoY-4,HenrDe00
4,3,Jahmyr Gibbs,22,DET,RB,17,4,63,52,517,...,5.6,83.1,14.7,302,6.4,1929,20,1,PBAP OPoY-8,GibbJa01
5,4,Bijan Robinson,22,ATL,RB,17,17,72,61,431,...,4.8,85.6,17.9,365,5.2,1887,15,1,PB,RobiBi01
6,5,Ja'Marr Chase,24,CIN,WR,17,16,175,127,1708,...,10.7,1.9,0.2,130,13.4,1740,17,0,PBAP-1AP MVP-8AP OPoY-3,ChasJa00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
618,590,Dominick Puni,24,SFO,RG,17,17,0,0,-3,...,NaN,0.0,0.0,0,NaN,-3,0,0,NaN,PuniDo00
619,591,Kadarius Toney,25,CLE,WR,3,0,1,0,0,...,-2.0,-1.3,0.7,2,-2.0,-4,0,1,NaN,ToneKa00
620,592,Kyle Trask,26,TAM,QB,4,0,0,0,0,...,-0.8,-1.0,1.3,5,-0.8,-4,0,0,NaN,TrasKy00
621,593,Clayton Tune,25,ARI,QB,6,0,0,0,0,...,-0.6,-0.7,1.2,7,-0.6,-4,0,1,NaN,TuneCl00
622,594,Tyson Bagent,24,CHI,QB,4,0,0,0,0,...,-1.2,-1.8,1.5,6,-1.2,-7,0,0,NaN,BageTy00

In [405]:
player_data_df.columns = column_names



player_data_df.head()

,Rk,Player,Age,Team,Pos,G,GS,Receiving Tgt,Receiving Rec,Receiving Yds,...,Rushing Y/A,Rushing Y/G,Rushing A/G,Scrimmage Touch,Scrimmage Y/Tch,Scrimmage YScm,Scrimmage RRTD,Fmb,Awards,-additional -9999
2,1,Saquon Barkley,27,PHI,RB,16,16,43,33,278,...,5.8,125.3,21.6,378,6.0,2283,15,2,PBAP-1AP MVP-3AP OPoY-1AP CPoY-14,BarkSa00
3,2,Derrick Henry,30,BAL,RB,17,17,22,19,193,...,5.9,113.0,19.1,344,6.1,2114,18,3,PBAP-2AP OPoY-4,HenrDe00
4,3,Jahmyr Gibbs,22,DET,RB,17,4,63,52,517,...,5.6,83.1,14.7,302,6.4,1929,20,1,PBAP OPoY-8,GibbJa01
5,4,Bijan Robinson,22,ATL,RB,17,17,72,61,431,...,4.8,85.6,17.9,365,5.2,1887,15,1,PB,RobiBi01
6,5,Ja'Marr Chase,24,CIN,WR,17,16,175,127,1708,...,10.7,1.9,0.2,130,13.4,1740,17,0,PBAP-1AP MVP-8AP OPoY-3,ChasJa00

In [406]:
column_names
keep_cols =[
 ' Player',' Age',' Team',' Pos',' G','Receiving Tgt','Receiving Rec','Receiving Yds',
 'Receiving Y/R','Receiving TD','Rushing Att','Rushing Yds','Rushing TD','Scrimmage Touch','Scrimmage YScm',
 'Scrimmage RRTD']
player_data_df = player_data_df[keep_cols]
player_data_df.head()

,Player,Age,Team,Pos,G,Receiving Tgt,Receiving Rec,Receiving Yds,Receiving Y/R,Receiving TD,Rushing Att,Rushing Yds,Rushing TD,Scrimmage Touch,Scrimmage YScm,Scrimmage RRTD
2,Saquon Barkley,27,PHI,RB,16,43,33,278,8.4,2,345,2005,13,378,2283,15
3,Derrick Henry,30,BAL,RB,17,22,19,193,10.2,2,325,1921,16,344,2114,18
4,Jahmyr Gibbs,22,DET,RB,17,63,52,517,9.9,4,250,1412,16,302,1929,20
5,Bijan Robinson,22,ATL,RB,17,72,61,431,7.1,1,304,1456,14,365,1887,15
6,Ja'Marr Chase,24,CIN,WR,17,175,127,1708,13.4,17,3,32,0,130,1740,17

In [407]:
pd.set_option('display.max_rows',100)
player_data_df.head(100)

,Player,Age,Team,Pos,G,Receiving Tgt,Receiving Rec,Receiving Yds,Receiving Y/R,Receiving TD,Rushing Att,Rushing Yds,Rushing TD,Scrimmage Touch,Scrimmage YScm,Scrimmage RRTD
2,Saquon Barkley,27,PHI,RB,16,43,33,278,8.4,2,345,2005,13,378,2283,15
3,Derrick Henry,30,BAL,RB,17,22,19,193,10.2,2,325,1921,16,344,2114,18
4,Jahmyr Gibbs,22,DET,RB,17,63,52,517,9.9,4,250,1412,16,302,1929,20
5,Bijan Robinson,22,ATL,RB,17,72,61,431,7.1,1,304,1456,14,365,1887,15
6,Ja'Marr Chase,24,CIN,WR,17,175,127,1708,13.4,17,3,32,0,130,1740,17
7,Josh Jacobs,26,GNB,RB,17,43,36,342,9.5,1,301,1329,15,337,1671,16
8,Jonathan Taylor,25,IND,RB,14,31,18,136,7.6,1,303,1431,11,321,1567,12
9,Aaron Jones,30,MIN,RB,17,62,51,408,8.0,2,255,1138,5,306,1546,7
10,Justin Jefferson,25,MIN,WR,17,154,103,1533,14.9,10,1,3,0,104,1536,10
11,Bucky Irving,22,TAM,RB,17,52,47,392,8.3,0,207,1122,8,254,1514,8
12,James Conner,29,ARI,RB,16,55,47,414,8.8,1,236,1094,8,283,1508,9
13,De'Von Achane,23,MIA,RB,17,87,78,592,7.6,6,203,907,6,281,1499,12
14,Alvin Kamara,29,NOR,RB,14,89,68,543,8.0,2,228,950,6,296,1493,8
15,Kyren Williams,24,LAR,RB,16,40,34,182,5.4,2,316,1299,14,350,1481,16
16,Chuba Hubbard,25,CAR,RB,15,54,43,171,4.0,1,250,1195,10,293,1366,11
17,Breece Hall,23,NYJ,RB,16,76,57,483,8.5,3,209,876,5,266,1359,8
18,Chase Brown,24,CIN,RB,16,65,54,360,6.7,4,229,990,7,283,1350,11
19,D'Andre Swift,25,CHI,RB,17,52,42,386,9.2,0,253,959,6,295,1345,6
20,Brian Thomas,22,JAX,WR,17,133,87,1282,14.7,10,6,48,0,93,1330,10
21,Rico Dowdle,26,DAL,RB,16,49,39,249,6.4,3,235,1079,2,274,1328,5
22,Najee Harris,26,PIT,RB,17,48,36,283,7.9,0,263,1043,6,299,1326,6
23,Joe Mixon,28,HOU,RB,14,52,36,309,8.6,1,245,1016,11,281,1325,12
24,Tony Pollard,27,TEN,RB,16,57,41,238,5.8,0,260,1079,5,301,1317,5
25,Amon-Ra St. Brown,25,DET,WR,17,141,115,1263,11.0,12,2,6,0,117,1269,12
26,Drake London,23,ATL,WR,17,158,100,1271,12.7,9,1,-3,0,101,1268,9
27,James Cook,25,BUF,RB,16,38,32,258,8.1,2,207,1009,16,239,1267,18
28,CeeDee Lamb,25,DAL,WR,15,152,101,1194,11.8,6,14,70,0,115,1264,6
29,Jerry Jeudy,25,CLE,WR,17,145,90,1229,13.7,4,0,0,0,90,1229,4
30,Brock Bowers,22,LVR,TE,17,153,112,1194,10.7,5,5,13,0,117,1207,5
31,Malik Nabers,21,NYG,WR,15,170,109,1204,11.0,7,5,2,0,114,1206,7
32,Jaxon Smith-Njigba,22,SEA,WR,17,137,100,1130,11.3,6,5,26,0,105,1156,6
33,Ladd McConkey,23,LAC,WR,16,112,82,1149,14.0,7,0,0,0,82,1149,7
34,Trey McBride,25,ARI,TE,16,147,111,1146,10.3,2,1,2,1,112,1148,3
35,Tyrone Tracy Jr.,25,NYG,RB,17,53,38,284,7.5,1,192,839,5,230,1123,6
36,David Montgomery,27,DET,RB,14,38,36,341,9.5,0,185,775,12,221,1116,12
37,Zay Flowers,24,BAL,WR,17,116,74,1059,14.3,4,9,56,0,83,1115,4
38,Garrett Wilson,24,NYJ,WR,17,154,101,1104,10.9,7,2,5,0,103,1109,7
39,George Kittle,31,SFO,TE,15,94,78,1106,14.2,8,0,0,0,78,1106,8
40,Terry McLaurin,29,WAS,WR,17,117,82,1096,13.4,13,2,2,0,84,1098,13
41,Courtland Sutton,29,DEN,WR,17,135,81,1081,13.3,8,0,0,0,81,1081,8
42,A.J. Brown,27,PHI,WR,13,97,67,1079,16.1,7,0,0,0,67,1079,7
43,Calvin Ridley,30,TEN,WR,17,120,64,1017,15.9,4,8,55,1,72,1072,5
44,Davante Adams,32,2TM,WR,14,141,85,1063,12.5,8,0,0,0,85,1063,8
45,Davante Adams,32,LVR,WR,3,27,18,209,11.6,1,0,0,0,18,209,1
46,Davante Adams,32,NYJ,WR,11,114,67,854,12.7,7,0,0,0,67,854,7
47,Jameson Williams,23,DET,WR,15,91,58,1001,17.3,7,11,61,1,69,1062,8
48,J.K. Dobbins,26,LAC,RB,13,38,32,153,4.8,0,195,905,9,227,1058,9
49,Jakobi Meyers,28,LVR,WR,15,129,87,1027,11.8,4,2,23,0,89,1050,4
50,D.J. Moore,27,CHI,WR,17,140,98,966,9.9,6,14,75,0,112,1041,6
51,Puka Nacua,23,LAR,WR,11,106,79,990,12.5,3,11,46,1,90,1036,4
52,Jayden Reed,24,GNB,WR,17,75,55,857,15.6,6,20,163,1,75,1020,7
53,Tyreek Hill,30,MIA,WR,17,123,81,959,11.8,6,8,53,0,89,1012,6
54,Nico Collins,25,HOU,WR,12,99,68,1006,14.8,7,0,0,0,68,1006,7
55,Rachaad White,25,TAM,RB,16,57,51,393,7.7,6,144,613,3,195,1006,9
56,Mike Evans,31,TAM,WR,14,110,74,1004,13.6,11,0,0,0,74,1004,11
57,D.K. Metcalf,27,SEA,WR,15,108,66,992,15.0,5,0,0,0,66,992,5
58,Darnell Mooney,27,ATL,WR,16,106,64,992,15.5,5,0,0,0,64,992,5
59,Jauan Jennings,27,SFO,WR,15,113,77,975,12.7,6,0,0,0,77,975,6
60,Rhamondre Stevenson,26,NWE,RB,15,41,33,168,5.1,1,207,801,7,240,969,8
61,Brian Robinson Jr.,25,WAS,RB,14,25,20,159,8.0,0,187,799,8,207,958,8
62,Lamar Jackson,27,BAL,QB,17,0,0,0,NaN,0,139,915,4,139,915,4
63,Tee Higgins,25,CIN,WR,12,109,73,911,12.5,10,0,0,0,73,911,10
64,Zach Charbonnet,23,SEA,RB,17,52,42,340,8.1,1,135,569,8,177,909,9
65,Kareem Hunt,29,KAN,RB,13,32,23,176,7.7,0,200,728,7,223,904,7
66,Jordan Addison,22,MIN,WR,15,99,63,875,13.9,9,3,20,1,66,895,10
67,George Pickens,23,PIT,WR,14,103,59,900,15.3,3,2,-6,0,61,894,3
68,Jayden Daniels,24,WAS,QB,17,0,0,0,NaN,0,148,891,6,148,891,6
69,Marvin Harrison Jr.,22,ARI,WR,17,116,62,885,14.3,8,0,0,0,62,885,8
70,Jonnu Smith,29,MIA,TE,17,111,88,884,10.0,8,2,-1,0,90,883,8
71,Jordan Mason,25,SFO,RB,12,14,11,91,8.3,0,153,789,3,164,880,3
72,Kenneth Walker III,24,SEA,RB,11,53,46,299,6.5,1,153,573,7,199,872,8
73,Javonte Williams,24,DEN,RB,17,70,52,346,6.7,0,139,513,4,191,859,4
74,DeVonta Smith,26,PHI,WR,13,89,68,833,12.3,8,1,1,0,69,834,8
75,Khalil Shakir,24,BUF,WR,15,100,76,821,10.8,4,2,4,0,78,825,4
76,Travis Kelce,35,KAN,TE,16,133,97,823,8.5,3,1,1,0,98,824,3
77,Alec Pierce,24,IND,WR,16,69,37,824,22.3,7,0,0,0,37,824,7
78,Jaylen Warren,26,PIT,RB,15,47,38,310,8.2,0,120,511,1,158,821,1
79,Tank Bigsby,23,JAX,RB,16,12,7,54,7.7,0,168,766,7,175,820,7
80,Josh Downs,23,IND,WR,14,107,72,803,11.2,5,1,12,0,73,815,5
81,Travis Etienne,25,JAX,RB,15,52,39,254,6.5,0,150,558,2,189,812,2
82,Michael Pittman Jr.,27,IND,WR,16,111,69,808,11.7,3,0,0,0,69,808,3
83,Deebo Samuel,28,SFO,WR,15,81,51,670,13.1,3,42,136,1,93,806,4
84,Jerome Ford,25,CLE,RB,14,43,37,225,6.1,0,104,565,3,141,790,3
85,Ray-Ray McCloud,28,ATL,WR,17,87,62,686,11.1,1,10,79,0,72,765,1
86,Rashod Bateman,25,BAL,WR,17,72,45,756,16.8,9,0,0,0,45,756,9
87,Jaylen Waddle,26,MIA,WR,15,83,58,744,12.8,2,4,12,0,62,756,2
88,Rome Odunze,22,CHI,WR,17,101,54,734,13.6,3,3,15,0,57,749,3
89,Keenan Allen,32,CHI,WR,15,121,70,744,10.6,7,0,0,0,70,744,7
90,Antonio Gibson,26,NWE,RB,17,29,23,206,9.0,0,120,538,1,143,744,1
91,Xavier Worthy,21,KAN,WR,17,98,59,638,10.8,6,20,104,3,79,742,9
92,Austin Ekeler,29,WAS,RB,12,41,35,366,10.5,0,77,367,4,112,733,4
93,Tyler Allgeier,24,ATL,RB,17,13,13,88,6.8,0,137,644,3,150,732,3
94,Sam LaPorta,23,DET,TE,16,83,60,726,12.1,7,0,0,0,60,726,7
95,Cooper Kupp,31,LAR,WR,12,100,67,710,10.6,6,2,10,0,69,720,6
96,Quentin Johnston,23,LAC,WR,15,91,55,711,12.9,8,3,6,0,58,717,8
97,Wan'Dale Robinson,23,NYG,WR,17,140,93,699,7.5,3,3,18,0,96,717,3
98,Alexander Mattison,26,LVR,RB,14,48,36,294,8.2,1,132,420,4,168,714,5
99,Tucker Kraft,24,GNB,TE,17,70,50,707,14.1,7,3,6,0,53,713,7
100,Tank Dell,25,HOU,WR,14,81,51,667,13.1,3,9,43,0,60,710,3
101,Mark Andrews,29,BAL,TE,17,69,55,673,12.2,11,4,5,0,59,678,11

In [408]:
vc =player_data_df[' Player'].value_counts()
multi_team_player = vc[vc > 1].index
multi_team_player_df = player_data_df[player_data_df[' Player'].isin(multi_team_player)]
multi_team_player_df=multi_team_player_df[multi_team_player_df[' Team'].str.contains('TM')]

In [409]:
single_team_player_df = player_data_df[~player_data_df[' Player'].isin(multi_team_player)]
player_dfs = [single_team_player_df,multi_team_player_df]
player_df = pd.concat(player_dfs)
player_df.head(100)

,Player,Age,Team,Pos,G,Receiving Tgt,Receiving Rec,Receiving Yds,Receiving Y/R,Receiving TD,Rushing Att,Rushing Yds,Rushing TD,Scrimmage Touch,Scrimmage YScm,Scrimmage RRTD
2,Saquon Barkley,27,PHI,RB,16,43,33,278,8.4,2,345,2005,13,378,2283,15
3,Derrick Henry,30,BAL,RB,17,22,19,193,10.2,2,325,1921,16,344,2114,18
4,Jahmyr Gibbs,22,DET,RB,17,63,52,517,9.9,4,250,1412,16,302,1929,20
5,Bijan Robinson,22,ATL,RB,17,72,61,431,7.1,1,304,1456,14,365,1887,15
6,Ja'Marr Chase,24,CIN,WR,17,175,127,1708,13.4,17,3,32,0,130,1740,17
7,Josh Jacobs,26,GNB,RB,17,43,36,342,9.5,1,301,1329,15,337,1671,16
8,Jonathan Taylor,25,IND,RB,14,31,18,136,7.6,1,303,1431,11,321,1567,12
9,Aaron Jones,30,MIN,RB,17,62,51,408,8.0,2,255,1138,5,306,1546,7
10,Justin Jefferson,25,MIN,WR,17,154,103,1533,14.9,10,1,3,0,104,1536,10
11,Bucky Irving,22,TAM,RB,17,52,47,392,8.3,0,207,1122,8,254,1514,8
12,James Conner,29,ARI,RB,16,55,47,414,8.8,1,236,1094,8,283,1508,9
13,De'Von Achane,23,MIA,RB,17,87,78,592,7.6,6,203,907,6,281,1499,12
14,Alvin Kamara,29,NOR,RB,14,89,68,543,8.0,2,228,950,6,296,1493,8
15,Kyren Williams,24,LAR,RB,16,40,34,182,5.4,2,316,1299,14,350,1481,16
16,Chuba Hubbard,25,CAR,RB,15,54,43,171,4.0,1,250,1195,10,293,1366,11
17,Breece Hall,23,NYJ,RB,16,76,57,483,8.5,3,209,876,5,266,1359,8
18,Chase Brown,24,CIN,RB,16,65,54,360,6.7,4,229,990,7,283,1350,11
19,D'Andre Swift,25,CHI,RB,17,52,42,386,9.2,0,253,959,6,295,1345,6
20,Brian Thomas,22,JAX,WR,17,133,87,1282,14.7,10,6,48,0,93,1330,10
21,Rico Dowdle,26,DAL,RB,16,49,39,249,6.4,3,235,1079,2,274,1328,5
22,Najee Harris,26,PIT,RB,17,48,36,283,7.9,0,263,1043,6,299,1326,6
23,Joe Mixon,28,HOU,RB,14,52,36,309,8.6,1,245,1016,11,281,1325,12
24,Tony Pollard,27,TEN,RB,16,57,41,238,5.8,0,260,1079,5,301,1317,5
25,Amon-Ra St. Brown,25,DET,WR,17,141,115,1263,11.0,12,2,6,0,117,1269,12
26,Drake London,23,ATL,WR,17,158,100,1271,12.7,9,1,-3,0,101,1268,9
27,James Cook,25,BUF,RB,16,38,32,258,8.1,2,207,1009,16,239,1267,18
28,CeeDee Lamb,25,DAL,WR,15,152,101,1194,11.8,6,14,70,0,115,1264,6
29,Jerry Jeudy,25,CLE,WR,17,145,90,1229,13.7,4,0,0,0,90,1229,4
30,Brock Bowers,22,LVR,TE,17,153,112,1194,10.7,5,5,13,0,117,1207,5
31,Malik Nabers,21,NYG,WR,15,170,109,1204,11.0,7,5,2,0,114,1206,7
32,Jaxon Smith-Njigba,22,SEA,WR,17,137,100,1130,11.3,6,5,26,0,105,1156,6
33,Ladd McConkey,23,LAC,WR,16,112,82,1149,14.0,7,0,0,0,82,1149,7
34,Trey McBride,25,ARI,TE,16,147,111,1146,10.3,2,1,2,1,112,1148,3
35,Tyrone Tracy Jr.,25,NYG,RB,17,53,38,284,7.5,1,192,839,5,230,1123,6
36,David Montgomery,27,DET,RB,14,38,36,341,9.5,0,185,775,12,221,1116,12
37,Zay Flowers,24,BAL,WR,17,116,74,1059,14.3,4,9,56,0,83,1115,4
38,Garrett Wilson,24,NYJ,WR,17,154,101,1104,10.9,7,2,5,0,103,1109,7
39,George Kittle,31,SFO,TE,15,94,78,1106,14.2,8,0,0,0,78,1106,8
40,Terry McLaurin,29,WAS,WR,17,117,82,1096,13.4,13,2,2,0,84,1098,13
41,Courtland Sutton,29,DEN,WR,17,135,81,1081,13.3,8,0,0,0,81,1081,8
42,A.J. Brown,27,PHI,WR,13,97,67,1079,16.1,7,0,0,0,67,1079,7
43,Calvin Ridley,30,TEN,WR,17,120,64,1017,15.9,4,8,55,1,72,1072,5
47,Jameson Williams,23,DET,WR,15,91,58,1001,17.3,7,11,61,1,69,1062,8
48,J.K. Dobbins,26,LAC,RB,13,38,32,153,4.8,0,195,905,9,227,1058,9
49,Jakobi Meyers,28,LVR,WR,15,129,87,1027,11.8,4,2,23,0,89,1050,4
50,D.J. Moore,27,CHI,WR,17,140,98,966,9.9,6,14,75,0,112,1041,6
51,Puka Nacua,23,LAR,WR,11,106,79,990,12.5,3,11,46,1,90,1036,4
52,Jayden Reed,24,GNB,WR,17,75,55,857,15.6,6,20,163,1,75,1020,7
53,Tyreek Hill,30,MIA,WR,17,123,81,959,11.8,6,8,53,0,89,1012,6
54,Nico Collins,25,HOU,WR,12,99,68,1006,14.8,7,0,0,0,68,1006,7
55,Rachaad White,25,TAM,RB,16,57,51,393,7.7,6,144,613,3,195,1006,9
56,Mike Evans,31,TAM,WR,14,110,74,1004,13.6,11,0,0,0,74,1004,11
57,D.K. Metcalf,27,SEA,WR,15,108,66,992,15.0,5,0,0,0,66,992,5
58,Darnell Mooney,27,ATL,WR,16,106,64,992,15.5,5,0,0,0,64,992,5
59,Jauan Jennings,27,SFO,WR,15,113,77,975,12.7,6,0,0,0,77,975,6
60,Rhamondre Stevenson,26,NWE,RB,15,41,33,168,5.1,1,207,801,7,240,969,8
61,Brian Robinson Jr.,25,WAS,RB,14,25,20,159,8.0,0,187,799,8,207,958,8
62,Lamar Jackson,27,BAL,QB,17,0,0,0,NaN,0,139,915,4,139,915,4
63,Tee Higgins,25,CIN,WR,12,109,73,911,12.5,10,0,0,0,73,911,10
64,Zach Charbonnet,23,SEA,RB,17,52,42,340,8.1,1,135,569,8,177,909,9
65,Kareem Hunt,29,KAN,RB,13,32,23,176,7.7,0,200,728,7,223,904,7
66,Jordan Addison,22,MIN,WR,15,99,63,875,13.9,9,3,20,1,66,895,10
67,George Pickens,23,PIT,WR,14,103,59,900,15.3,3,2,-6,0,61,894,3
68,Jayden Daniels,24,WAS,QB,17,0,0,0,NaN,0,148,891,6,148,891,6
69,Marvin Harrison Jr.,22,ARI,WR,17,116,62,885,14.3,8,0,0,0,62,885,8
70,Jonnu Smith,29,MIA,TE,17,111,88,884,10.0,8,2,-1,0,90,883,8
71,Jordan Mason,25,SFO,RB,12,14,11,91,8.3,0,153,789,3,164,880,3
72,Kenneth Walker III,24,SEA,RB,11,53,46,299,6.5,1,153,573,7,199,872,8
73,Javonte Williams,24,DEN,RB,17,70,52,346,6.7,0,139,513,4,191,859,4
74,DeVonta Smith,26,PHI,WR,13,89,68,833,12.3,8,1,1,0,69,834,8
75,Khalil Shakir,24,BUF,WR,15,100,76,821,10.8,4,2,4,0,78,825,4
76,Travis Kelce,35,KAN,TE,16,133,97,823,8.5,3,1,1,0,98,824,3
77,Alec Pierce,24,IND,WR,16,69,37,824,22.3,7,0,0,0,37,824,7
78,Jaylen Warren,26,PIT,RB,15,47,38,310,8.2,0,120,511,1,158,821,1
79,Tank Bigsby,23,JAX,RB,16,12,7,54,7.7,0,168,766,7,175,820,7
80,Josh Downs,23,IND,WR,14,107,72,803,11.2,5,1,12,0,73,815,5
81,Travis Etienne,25,JAX,RB,15,52,39,254,6.5,0,150,558,2,189,812,2
82,Michael Pittman Jr.,27,IND,WR,16,111,69,808,11.7,3,0,0,0,69,808,3
83,Deebo Samuel,28,SFO,WR,15,81,51,670,13.1,3,42,136,1,93,806,4
84,Jerome Ford,25,CLE,RB,14,43,37,225,6.1,0,104,565,3,141,790,3
85,Ray-Ray McCloud,28,ATL,WR,17,87,62,686,11.1,1,10,79,0,72,765,1
86,Rashod Bateman,25,BAL,WR,17,72,45,756,16.8,9,0,0,0,45,756,9
87,Jaylen Waddle,26,MIA,WR,15,83,58,744,12.8,2,4,12,0,62,756,2
88,Rome Odunze,22,CHI,WR,17,101,54,734,13.6,3,3,15,0,57,749,3
89,Keenan Allen,32,CHI,WR,15,121,70,744,10.6,7,0,0,0,70,744,7
90,Antonio Gibson,26,NWE,RB,17,29,23,206,9.0,0,120,538,1,143,744,1
91,Xavier Worthy,21,KAN,WR,17,98,59,638,10.8,6,20,104,3,79,742,9
92,Austin Ekeler,29,WAS,RB,12,41,35,366,10.5,0,77,367,4,112,733,4
93,Tyler Allgeier,24,ATL,RB,17,13,13,88,6.8,0,137,644,3,150,732,3
94,Sam LaPorta,23,DET,TE,16,83,60,726,12.1,7,0,0,0,60,726,7
95,Cooper Kupp,31,LAR,WR,12,100,67,710,10.6,6,2,10,0,69,720,6
96,Quentin Johnston,23,LAC,WR,15,91,55,711,12.9,8,3,6,0,58,717,8
97,Wan'Dale Robinson,23,NYG,WR,17,140,93,699,7.5,3,3,18,0,96,717,3
98,Alexander Mattison,26,LVR,RB,14,48,36,294,8.2,1,132,420,4,168,714,5
99,Tucker Kraft,24,GNB,TE,17,70,50,707,14.1,7,3,6,0,53,713,7
100,Tank Dell,25,HOU,WR,14,81,51,667,13.1,3,9,43,0,60,710,3
101,Mark Andrews,29,BAL,TE,17,69,55,673,12.2,11,4,5,0,59,678,11
102,Hunter Henry,30,NWE,TE,16,97,66,674,10.2,2,0,0,0,66,674,2
103,Mike Gesicki,29,CIN,TE,17,83,65,665,10.2,2,0,0,0,65,665,2
104,Zach Ertz,34,WAS,TE,17,91,66,654,9.9,7,0,0,0,66,654,7

In [410]:
player_df[' Pos'].value_counts()
keep_QB = ['QB']
qb_scrimmage_df = player_df[player_df[' Pos'].isin(keep_QB)].copy()
keep_pos = ['WR','RB','TE']
player_df = player_df[player_df[' Pos'].isin(keep_pos)]
qb_scrimmage_df

,Player,Age,Team,Pos,G,Receiving Tgt,Receiving Rec,Receiving Yds,Receiving Y/R,Receiving TD,Rushing Att,Rushing Yds,Rushing TD,Scrimmage Touch,Scrimmage YScm,Scrimmage RRTD
62,Lamar Jackson,27,BAL,QB,17,0,0,0,NaN,0,139,915,4,139,915,4
68,Jayden Daniels,24,WAS,QB,17,0,0,0,NaN,0,148,891,6,148,891,6
109,Jalen Hurts,26,PHI,QB,15,0,0,0,NaN,0,150,630,14,150,630,14
128,Kyler Murray,27,ARI,QB,17,0,0,0,NaN,0,78,572,5,78,572,5
141,Josh Allen,28,BUF,QB,17,0,0,7,NaN,1,102,531,12,102,538,13
156,Anthony Richardson,22,IND,QB,11,1,1,-1,-1.0,0,86,499,6,87,498,6
162,Caleb Williams,23,CHI,QB,17,0,0,0,NaN,0,81,489,0,81,489,0
179,Bo Nix,24,DEN,QB,17,1,1,2,2.0,1,92,430,4,93,432,5
181,Drake Maye,22,NWE,QB,13,0,0,0,NaN,0,54,421,2,54,421,2
205,Baker Mayfield,29,TAM,QB,17,0,0,0,NaN,0,60,378,3,60,378,3
222,Brock Purdy,25,SFO,QB,15,0,0,0,NaN,0,66,323,5,66,323,5
227,Patrick Mahomes,29,KAN,QB,16,1,1,2,2.0,0,58,307,2,59,309,2
228,Justin Herbert,26,LAC,QB,17,0,0,0,NaN,0,69,306,2,69,306,2
239,Justin Fields,25,PIT,QB,10,0,0,0,NaN,0,62,289,5,62,289,5
245,Geno Smith,34,SEA,QB,17,0,0,0,NaN,0,53,272,2,53,272,2
249,Daniel Jones,27,NYG,QB,10,0,0,0,NaN,0,67,265,2,67,265,2
258,Bryce Young,23,CAR,QB,14,0,0,0,NaN,0,43,249,6,43,249,6
266,C.J. Stroud,23,HOU,QB,17,1,0,0,NaN,0,52,233,0,52,233,0
278,Sam Darnold,27,MIN,QB,17,0,0,0,NaN,0,67,212,1,67,212,1
286,Joe Burrow,28,CIN,QB,17,0,0,0,NaN,0,42,201,2,42,201,2
297,Will Levis,25,TEN,QB,12,0,0,0,NaN,0,45,183,0,45,183,0
312,Russell Wilson,36,PIT,QB,11,0,0,0,NaN,0,43,155,2,43,155,2
320,Deshaun Watson,29,CLE,QB,7,0,0,0,NaN,0,31,148,1,31,148,1
322,Spencer Rattler,24,NOR,QB,7,0,0,0,NaN,0,18,146,0,18,146,0
327,Malik Willis,25,GNB,QB,7,0,0,0,NaN,0,20,138,1,20,138,1
328,Tyler Huntley,26,MIA,QB,5,0,0,0,NaN,0,26,135,2,26,135,2
331,Drew Lock,28,NYG,QB,8,0,0,0,NaN,0,18,133,2,18,133,2
339,Dorian Thompson-Robinson,25,CLE,QB,7,0,0,0,NaN,0,21,122,0,21,122,0
346,Trevor Lawrence,25,JAX,QB,10,0,0,-5,NaN,0,26,119,3,26,114,3
354,Aaron Rodgers,41,NYJ,QB,17,0,0,0,NaN,0,22,107,0,22,107,0
356,Mason Rudolph,29,TEN,QB,8,0,0,0,NaN,0,25,106,1,25,106,1
367,Mac Jones,26,JAX,QB,10,0,0,0,NaN,0,28,92,1,28,92,1
368,Marcus Mariota,31,WAS,QB,3,0,0,0,NaN,0,18,92,1,18,92,1
379,Jordan Love,26,GNB,QB,15,0,0,0,NaN,0,25,83,1,25,83,1
381,Jameis Winston,30,CLE,QB,12,0,0,0,NaN,0,25,83,1,25,83,1
390,Derek Carr,33,NOR,QB,10,0,0,0,NaN,0,17,71,1,17,71,1
401,Jared Goff,30,DET,QB,17,1,1,7,7.0,1,35,56,0,36,63,1
402,Jacoby Brissett,32,NWE,QB,8,0,0,0,NaN,0,15,62,0,15,62,0
406,Gardner Minshew II,28,LVR,QB,10,0,0,0,NaN,0,19,58,0,19,58,0
411,Dak Prescott,31,DAL,QB,8,0,0,0,NaN,0,13,54,1,13,54,1
418,Tua Tagovailoa,26,MIA,QB,11,0,0,0,NaN,0,17,49,0,17,49,0
435,Trey Lance,24,DAL,QB,4,0,0,0,NaN,0,11,41,0,11,41,0
437,Matthew Stafford,36,LAR,QB,16,0,0,0,NaN,0,30,41,0,30,41,0
450,Desmond Ridder,25,LVR,QB,6,0,0,0,NaN,0,9,36,0,9,36,0
453,Andy Dalton,37,CAR,QB,6,0,0,0,NaN,0,11,34,0,11,34,0
457,Tommy DeVito,26,NYG,QB,3,0,0,0,NaN,0,8,32,0,8,32,0
466,Aidan O'Connell,26,LVR,QB,9,0,0,0,NaN,0,21,30,1,21,30,1
475,Joe Flacco,39,IND,QB,8,0,0,0,NaN,0,9,26,0,9,26,0
476,Joshua Dobbs,29,SFO,QB,2,0,0,0,NaN,0,9,24,2,9,24,2
481,Jake Haener,25,NOR,QB,8,0,0,0,NaN,0,11,22,0,11,22,0
491,Taylor Heinicke,31,LAC,QB,4,0,0,0,NaN,0,2,20,0,2,20,0
496,Cooper Rush,31,DAL,QB,12,0,0,0,NaN,0,26,18,0,26,18,0
503,Joe Milton,24,NWE,QB,1,0,0,0,NaN,0,10,16,1,10,16,1
505,Kenny Pickett,26,PHI,QB,5,0,0,0,NaN,0,9,15,1,9,15,1
508,Tyrod Taylor,35,NYJ,QB,2,0,0,0,NaN,0,3,13,0,3,13,0
516,Davis Mills,26,HOU,QB,4,0,0,0,NaN,0,3,11,0,3,11,0
517,Michael Penix,24,ATL,QB,5,0,0,0,NaN,0,7,11,1,7,11,1
552,Jimmy Garoppolo,33,LAR,QB,1,0,0,0,NaN,0,2,5,0,2,5,0
554,Chris Oladokun,27,KAN,QB,1,0,0,0,NaN,0,1,5,0,1,5,0
556,Jarrett Stidham,28,DEN,QB,3,0,0,0,NaN,0,4,5,0,4,5,0
557,Brandon Allen,32,SFO,QB,3,0,0,0,NaN,0,3,4,0,3,4,0
560,Skylar Thompson,27,MIA,QB,3,0,0,0,NaN,0,1,4,0,1,4,0
567,Hendon Hooker,26,DET,QB,3,0,0,0,NaN,0,5,2,0,5,2,0
568,Sam Howell,24,SEA,QB,2,0,0,0,NaN,0,1,2,0,1,2,0
574,Bailey Zappe,25,CLE,QB,1,0,0,0,NaN,0,2,2,0,2,2,0
576,Josh Johnson,38,BAL,QB,6,0,0,0,NaN,0,4,1,0,4,1,0
580,Mitchell Trubisky,30,BUF,QB,9,0,0,0,NaN,0,17,1,0,17,1,0
588,Kirk Cousins,36,ATL,QB,14,0,0,0,NaN,0,23,0,0,23,0,0
608,Carson Wentz,32,KAN,QB,3,0,0,0,NaN,0,3,0,0,3,0,0
612,Tanner McKee,24,PHI,QB,2,0,0,0,NaN,0,5,-1,0,5,-1,0
613,Jake Browning,28,CIN,QB,3,0,0,0,NaN,0,2,-2,0,2,-2,0
615,Nick Mullens,29,MIN,QB,4,0,0,0,NaN,0,3,-2,0,3,-2,0
620,Kyle Trask,26,TAM,QB,4,0,0,0,NaN,0,5,-4,0,5,-4,0
621,Clayton Tune,25,ARI,QB,6,0,0,0,NaN,0,7,-4,0,7,-4,0
622,Tyson Bagent,24,CHI,QB,4,0,0,0,NaN,0,6,-7,0,6,-7,0
522,Tim Boyle,30,2TM,QB,3,0,0,0,NaN,0,3,9,0,3,9,0

In [411]:
player_df['Pts'] = player_df['Scrimmage YScm'].astype(float) / 10 + player_df['Scrimmage RRTD'].astype(float) * 6 + player_df['Receiving Rec'].astype(int)*1

In [412]:
player_df.sort_values('Pts',ascending=False)

,Player,Age,Team,Pos,G,Receiving Tgt,Receiving Rec,Receiving Yds,Receiving Y/R,Receiving TD,Rushing Att,Rushing Yds,Rushing TD,Scrimmage Touch,Scrimmage YScm,Scrimmage RRTD,Pts
6,Ja'Marr Chase,24,CIN,WR,17,175,127,1708,13.4,17,3,32,0,130,1740,17,403.0
4,Jahmyr Gibbs,22,DET,RB,17,63,52,517,9.9,4,250,1412,16,302,1929,20,364.9
2,Saquon Barkley,27,PHI,RB,16,43,33,278,8.4,2,345,2005,13,378,2283,15,351.3
5,Bijan Robinson,22,ATL,RB,17,72,61,431,7.1,1,304,1456,14,365,1887,15,339.7
3,Derrick Henry,30,BAL,RB,17,22,19,193,10.2,2,325,1921,16,344,2114,18,338.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,Irvin Charles,27,NYJ,WR,13,1,0,0,NaN,0,0,0,0,0,0,0,0.0
594,Tom Kennedy,28,DET,WR,4,1,0,0,NaN,0,0,0,0,0,0,0,0.0
596,Dylan Laube,25,LVR,RB,10,0,0,0,NaN,0,1,0,0,1,0,0,0.0
611,Jermaine Jackson,24,NOR,WR,4,0,0,0,NaN,0,1,-1,0,1,-1,0,-0.1
619,Kadarius Toney,25,CLE,WR,3,1,0,0,NaN,0,2,-4,0,2,-4,0,-0.4

In [413]:
dfqb = pd.read_csv("PassingYards2024.csv")
pd.set_option('display.max_rows',100)
dfqb = dfqb.drop(111)
dfqb.head(100)

,Rk,Player,Age,Team,Pos,G,GS,QBrec,Cmp,Att,...,QBR,Sk,Yds.1,Sk%,NY/A,ANY/A,4QC,GWD,Awards,Player-additional
0,1.0,Joe Burrow,28.0,CIN,QB,17.0,17.0,9-8-0,460.0,652.0,...,72.1,48.0,278.0,6.86,6.63,7.28,1.0,2.0,PBAP MVP-4AP OPoY-5AP CPoY-1,BurrJo01
1,2.0,Jared Goff,30.0,DET,QB,17.0,17.0,15-2-0,390.0,539.0,...,65.4,31.0,234.0,5.44,7.71,8.06,4.0,4.0,PBAP MVP-5AP OPoY-9,GoffJa00
2,3.0,Baker Mayfield,29.0,TAM,QB,17.0,17.0,10-7-0,407.0,570.0,...,58.4,40.0,248.0,6.56,6.97,7.13,2.0,2.0,PBAP MVP-11AP OPoY-11,MayfBa00
3,4.0,Geno Smith,34.0,SEA,QB,17.0,17.0,10-7-0,407.0,578.0,...,50.4,50.0,338.0,7.96,6.34,5.93,4.0,4.0,NaN,SmitGe00
4,5.0,Sam Darnold,27.0,MIN,QB,17.0,17.0,14-3-0,361.0,545.0,...,57.3,48.0,335.0,8.09,6.72,6.99,3.0,5.0,PBAP MVP-10AP CPoY-3,DarnSa00
5,6.0,Lamar Jackson,27.0,BAL,QB,17.0,17.0,12-5-0,316.0,474.0,...,74.8,23.0,149.0,4.63,8.09,9.38,2.0,2.0,PBAP-1AP MVP-2AP OPoY-2,JackLa00
6,7.0,Patrick Mahomes,29.0,KAN,QB,16.0,16.0,15-1-0,392.0,581.0,...,64.6,36.0,239.0,5.83,5.98,6.02,5.0,7.0,AP MVP-6AP OPoY-17,MahoPa00
7,8.0,Aaron Rodgers,41.0,NYJ,QB,17.0,17.0,5-12-0,368.0,584.0,...,44.7,40.0,302.0,6.41,5.76,5.87,2.0,3.0,AP CPoY-7,RodgAa00
8,9.0,Justin Herbert,26.0,LAC,QB,17.0,17.0,11-6-0,332.0,504.0,...,61.7,41.0,244.0,7.52,6.65,7.25,1.0,2.0,AP MVP-9AP CPoY-12,HerbJu00
9,10.0,Brock Purdy,25.0,SFO,QB,15.0,15.0,6-9-0,300.0,455.0,...,64.8,31.0,156.0,6.38,7.63,7.34,1.0,1.0,NaN,PurdBr00
10,11.0,Kyler Murray,27.0,ARI,QB,17.0,17.0,8-9-0,372.0,541.0,...,63.4,30.0,220.0,5.25,6.36,6.23,3.0,3.0,AP CPoY-10,MurrKy00
11,12.0,Bo Nix,24.0,DEN,QB,17.0,17.0,10-7-0,376.0,567.0,...,53.5,24.0,198.0,4.06,6.05,6.12,3.0,3.0,AP ORoY-3,NixxBo00
12,13.0,Matthew Stafford,36.0,LAR,QB,16.0,16.0,10-6-0,340.0,517.0,...,61.5,28.0,213.0,5.14,6.51,6.59,3.0,5.0,NaN,StafMa00
13,14.0,Josh Allen,28.0,BUF,QB,17.0,17.0,13-4-0,307.0,483.0,...,74.8,14.0,63.0,2.82,7.38,7.96,0.0,2.0,PBAP-2AP MVP-1AP OPoY-6,AlleJo02
14,15.0,C.J. Stroud,23.0,HOU,QB,17.0,17.0,10-7-0,336.0,532.0,...,46.4,52.0,408.0,8.90,5.68,5.44,1.0,2.0,NaN,StroCJ00
15,16.0,Jayden Daniels,24.0,WAS,QB,17.0,17.0,12-5-0,331.0,480.0,...,67.7,47.0,238.0,8.92,6.32,6.50,4.0,4.0,PBAP MVP-7AP OPoY-17AP ORoY-1,DaniJa02
16,17.0,Caleb Williams,23.0,CHI,QB,17.0,17.0,5-12-0,351.0,562.0,...,43.3,68.0,466.0,10.79,4.88,5.09,2.0,1.0,AP ORoY-10,WillCa03
17,18.0,Kirk Cousins,36.0,ATL,QB,14.0,14.0,7-7-0,303.0,453.0,...,47.0,28.0,201.0,5.82,6.88,6.13,3.0,3.0,AP CPoY-13,CousKi00
18,19.0,Jordan Love,26.0,GNB,QB,15.0,15.0,9-6-0,268.0,425.0,...,66.3,14.0,95.0,3.19,7.50,7.51,2.0,2.0,NaN,LoveJo03
19,20.0,Jalen Hurts,26.0,PHI,QB,15.0,15.0,12-3-0,248.0,361.0,...,62.5,38.0,271.0,9.52,6.60,6.93,3.0,4.0,NaN,HurtJa00
20,21.0,Tua Tagovailoa,26.0,MIA,QB,11.0,11.0,6-5-0,291.0,399.0,...,57.1,21.0,154.0,5.00,6.46,6.61,2.0,2.0,NaN,TagoTu00
21,22.0,Russell Wilson,36.0,PIT,QB,11.0,11.0,6-5-0,214.0,336.0,...,47.9,33.0,219.0,8.94,6.13,6.39,1.0,1.0,PBAP CPoY-14,WilsRu00
22,23.0,Bryce Young,23.0,CAR,QB,14.0,12.0,4-8-0,234.0,384.0,...,50.7,29.0,186.0,7.02,5.37,5.11,1.0,4.0,NaN,YounBr01
23,24.0,Drake Maye,22.0,NWE,QB,13.0,12.0,3-9-0,225.0,338.0,...,55.2,34.0,229.0,9.14,5.50,5.10,0.0,0.0,PBAP ORoY-8,MayeDr00
24,25.0,Derek Carr,33.0,NOR,QB,10.0,10.0,5-5-0,189.0,279.0,...,60.2,8.0,48.0,2.79,7.31,7.57,0.0,1.0,NaN,CarrDe02
25,26.0,Jameis Winston,30.0,CLE,QB,12.0,7.0,2-5-0,181.0,296.0,...,52.2,24.0,130.0,7.50,6.22,5.35,2.0,2.0,NaN,WinsJa00
26,27.0,Will Levis,25.0,TEN,QB,12.0,12.0,2-10-0,190.0,301.0,...,25.2,41.0,233.0,11.99,5.43,4.61,1.0,1.0,NaN,LeviWi00
27,28.0,Daniel Jones,27.0,NYG,QB,10.0,10.0,2-8-0,216.0,341.0,...,44.4,29.0,172.0,7.84,5.13,4.71,0.0,0.0,NaN,JoneDa05
28,29.0,Trevor Lawrence,25.0,JAX,QB,10.0,10.0,2-8-0,172.0,284.0,...,56.1,18.0,140.0,5.96,6.31,5.99,0.0,1.0,NaN,LawrTr00
29,30.0,Gardner Minshew II,28.0,LVR,QB,10.0,9.0,2-7-0,203.0,306.0,...,35.0,29.0,164.0,8.66,5.52,4.71,1.0,1.0,NaN,MinsGa00
30,31.0,Dak Prescott,31.0,DAL,QB,8.0,8.0,3-5-0,185.0,286.0,...,41.9,21.0,112.0,6.84,6.08,5.62,1.0,1.0,NaN,PresDa01
31,32.0,Cooper Rush,31.0,DAL,QB,12.0,8.0,4-4-0,187.0,308.0,...,37.8,13.0,95.0,4.05,5.45,5.50,0.0,0.0,NaN,RushCo00
32,33.0,Anthony Richardson,22.0,IND,QB,11.0,11.0,6-5-0,126.0,264.0,...,47.4,14.0,115.0,5.04,6.11,4.74,2.0,3.0,AP CPoY-25,RichAn03
33,34.0,Joe Flacco,39.0,IND,QB,8.0,6.0,2-4-0,162.0,248.0,...,50.0,18.0,123.0,6.77,6.16,5.88,1.0,2.0,NaN,FlacJo00
34,35.0,Mac Jones,26.0,JAX,QB,10.0,7.0,2-5-0,171.0,262.0,...,36.6,14.0,100.0,5.07,5.70,4.97,1.0,1.0,NaN,JoneMa05
35,36.0,Aidan O'Connell,26.0,LVR,QB,9.0,7.0,2-5-0,154.0,243.0,...,46.0,10.0,82.0,3.95,6.05,5.97,1.0,1.0,NaN,OConAi00
36,37.0,Mason Rudolph,29.0,TEN,QB,8.0,5.0,1-4-0,146.0,228.0,...,52.2,11.0,71.0,4.60,6.10,5.16,0.0,1.0,NaN,RudoMa00
37,38.0,Spencer Rattler,24.0,NOR,QB,7.0,6.0,0-6-0,130.0,228.0,...,37.1,22.0,136.0,8.80,4.72,4.14,0.0,0.0,NaN,RattSp00
38,39.0,Deshaun Watson,29.0,CLE,QB,7.0,7.0,1-6-0,137.0,216.0,...,21.0,33.0,191.0,13.25,3.84,3.70,0.0,0.0,NaN,WatsDe00
39,40.0,Justin Fields,25.0,PIT,QB,10.0,6.0,4-2-0,106.0,161.0,...,47.4,16.0,124.0,9.04,5.55,5.86,0.0,1.0,NaN,FielJu00
40,41.0,Drew Lock,28.0,NYG,QB,8.0,5.0,1-4-0,107.0,181.0,...,43.0,12.0,88.0,6.22,5.09,4.55,0.0,0.0,NaN,LockDr00
41,42.0,Andy Dalton,37.0,CAR,QB,6.0,5.0,1-4-0,106.0,160.0,...,52.0,7.0,37.0,4.19,5.70,4.92,0.0,0.0,NaN,DaltAn00
42,43.0,Tyler Huntley,26.0,MIA,QB,5.0,5.0,2-3-0,86.0,133.0,...,32.2,15.0,92.0,10.14,4.98,4.47,1.0,1.0,NaN,HuntTy01
43,44.0,Jacoby Brissett,32.0,NWE,QB,8.0,5.0,1-4-0,95.0,161.0,...,41.5,18.0,119.0,10.06,3.95,3.92,1.0,1.0,NaN,BrisJa00
44,45.0,Michael Penix,24.0,ATL,QB,5.0,3.0,1-2-0,61.0,105.0,...,47.6,4.0,14.0,3.67,6.98,6.29,0.0,0.0,NaN,PeniMi00
45,46.0,Malik Willis,25.0,GNB,QB,7.0,2.0,2-0-0,40.0,54.0,...,77.3,8.0,37.0,12.90,8.27,9.24,0.0,1.0,NaN,WillMa12
46,47.0,Desmond Ridder,25.0,LVR,QB,6.0,1.0,0-1-0,52.0,85.0,...,25.3,10.0,64.0,10.53,4.15,3.62,0.0,0.0,NaN,RiddDe00
47,48.0,Dorian Thompson-Robinson,25.0,CLE,QB,7.0,2.0,0-2-0,61.0,118.0,...,17.3,8.0,47.0,6.35,3.12,0.98,0.0,0.0,NaN,ThomDo02
48,49.0,Marcus Mariota,31.0,WAS,QB,3.0,0.0,NaN,34.0,44.0,...,86.3,3.0,29.0,6.38,7.13,8.83,1.0,1.0,NaN,MariMa01
49,50.0,Joshua Dobbs,29.0,SFO,QB,2.0,1.0,0-1-0,32.0,47.0,...,34.2,2.0,28.0,4.08,6.80,5.78,0.0,0.0,NaN,DobbJo00
50,51.0,Jimmy Garoppolo,33.0,LAR,QB,1.0,1.0,0-1-0,27.0,41.0,...,44.9,3.0,15.0,6.82,7.25,7.14,0.0,0.0,NaN,GaroJi00
51,52.0,Tanner McKee,24.0,PHI,QB,2.0,1.0,1-0-0,30.0,45.0,...,65.5,2.0,17.0,4.26,6.51,8.21,0.0,0.0,NaN,McKeTa01
52,53.0,Kenny Pickett,26.0,PHI,QB,5.0,1.0,1-0-0,25.0,42.0,...,73.1,4.0,33.0,8.70,5.61,5.50,0.0,0.0,NaN,PickKe00
53,54.0,Tim Boyle,30.0,2TM,QB,3.0,0.0,NaN,27.0,50.0,...,NaN,2.0,11.0,3.85,5.10,4.62,0.0,0.0,NaN,BoylTi00
54,54.0,Tim Boyle,30.0,MIA,QB,2.0,0.0,NaN,15.0,26.0,...,NaN,1.0,9.0,3.70,5.33,5.33,0.0,0.0,NaN,BoylTi00
55,54.0,Tim Boyle,30.0,NYG,QB,1.0,0.0,NaN,12.0,24.0,...,NaN,1.0,2.0,4.00,4.84,3.84,0.0,0.0,NaN,BoylTi00
56,55.0,Trey Lance,24.0,DAL,QB,4.0,1.0,0-1-0,25.0,41.0,...,35.2,4.0,23.0,8.89,5.40,4.40,0.0,0.0,NaN,LancTr00
57,56.0,Tommy DeVito,26.0,NYG,QB,3.0,2.0,0-2-0,31.0,44.0,...,24.4,6.0,31.0,12.00,4.52,4.52,0.0,0.0,NaN,DeViTo00
58,57.0,Joe Milton,24.0,NWE,QB,1.0,0.0,NaN,22.0,29.0,...,69.6,0.0,0.0,0.00,8.31,9.00,0.0,0.0,NaN,MiltJo00
59,58.0,Jake Haener,25.0,NOR,QB,8.0,1.0,0-1-0,18.0,39.0,...,12.8,6.0,55.0,13.33,3.80,3.24,0.0,0.0,NaN,HaenJa00
60,59.0,Davis Mills,26.0,HOU,QB,4.0,0.0,NaN,20.0,36.0,...,64.8,2.0,18.0,5.26,5.11,5.11,0.0,0.0,NaN,MillDa02
61,60.0,Brandon Allen,32.0,SFO,QB,3.0,1.0,0-1-0,17.0,30.0,...,31.4,2.0,2.0,6.25,6.16,3.97,0.0,0.0,NaN,AlleBr00
62,61.0,Skylar Thompson,27.0,MIA,QB,3.0,1.0,0-1-0,21.0,33.0,...,3.4,6.0,44.0,15.38,3.67,3.67,0.0,0.0,NaN,ThomSk00
63,62.0,Mitchell Trubisky,30.0,BUF,QB,9.0,0.0,NaN,19.0,26.0,...,57.8,0.0,0.0,0.00,6.88,8.42,0.0,0.0,NaN,TrubMi00
64,63.0,Bailey Zappe,25.0,CLE,QB,1.0,1.0,0-1-0,16.0,31.0,...,17.6,1.0,5.0,3.13,5.16,2.97,0.0,0.0,NaN,ZappBa00
65,64.0,Tyrod Taylor,35.0,NYJ,QB,2.0,0.0,NaN,17.0,22.0,...,95.0,0.0,0.0,0.00,5.41,8.14,0.0,0.0,NaN,TaylTy00
66,65.0,Carson Wentz,32.0,KAN,QB,3.0,1.0,0-1-0,12.0,19.0,...,20.6,4.0,22.0,17.39,4.17,4.17,0.0,0.0,NaN,WentCa00
67,66.0,Hendon Hooker,26.0,DET,QB,3.0,0.0,NaN,6.0,9.0,...,39.3,1.0,9.0,10.00,5.30,5.30,0.0,0.0,NaN,HookHe00
68,67.0,Nick Mullens,29.0,MIN,QB,4.0,0.0,NaN,2.0,2.0,...,97.5,0.0,0.0,0.00,19.00,19.00,0.0,0.0,NaN,MullNi00
69,68.0,Jaxon Smith-Njigba,22.0,SEA,WR,17.0,16.0,NaN,1.0,1.0,...,100.0,0.0,0.0,0.00,35.00,35.00,0.0,0.0,PB,SmitJa06
70,69.0,AJ Cole III,29.0,LVR,P,17.0,0.0,NaN,1.0,1.0,...,NaN,0.0,0.0,0.00,34.00,34.00,0.0,0.0,NaN,ColeAJ01
71,70.0,Courtland Sutton,29.0,DEN,WR,17.0,13.0,NaN,2.0,2.0,...,100.0,0.0,0.0,0.00,15.00,25.00,0.0,0.0,NaN,SuttCo00
72,71.0,Taylor Heinicke,31.0,LAC,QB,4.0,0.0,NaN,3.0,5.0,...,5.2,3.0,28.0,37.50,0.00,0.00,0.0,0.0,NaN,HeinTa00
73,72.0,Mike White,29.0,BUF,QB,1.0,0.0,NaN,3.0,11.0,...,12.4,0.0,0.0,0.00,2.55,2.55,0.0,0.0,NaN,WhitMi01
74,73.0,Sam Howell,24.0,SEA,QB,2.0,0.0,NaN,5.0,14.0,...,2.9,4.0,21.0,22.22,0.17,-2.33,0.0,0.0,NaN,HoweSa00
75,74.0,Adonai Mitchell,22.0,IND,WR,17.0,7.0,NaN,1.0,1.0,...,70.2,0.0,0.0,0.00,24.00,24.00,0.0,0.0,NaN,MitcAd00
76,75.0,Justin Jefferson,25.0,MIN,WR,17.0,17.0,NaN,1.0,1.0,...,23.7,0.0,0.0,0.00,22.00,22.00,0.0,0.0,PBAP-1AP OPoY-7,JeffJu00
77,76.0,Taysom Hill,34.0,NOR,TE,8.0,8.0,NaN,2.0,4.0,...,91.0,0.0,0.0,0.00,5.25,-6.00,0.0,0.0,NaN,HillTa00
78,77.0,Cedrick Wilson Jr.,29.0,NOR,WR,15.0,4.0,NaN,1.0,1.0,...,99.6,1.0,3.0,50.00,9.00,19.00,0.0,0.0,NaN,WilsCe01
79,78.0,Kyle Allen,28.0,PIT,QB,1.0,0.0,NaN,1.0,1.0,...,99.3,0.0,0.0,0.00,19.00,19.00,0.0,0.0,NaN,AlleKy00
80,79.0,Jalen Coker,23.0,CAR,WR,11.0,4.0,NaN,1.0,1.0,...,99.5,0.0,0.0,0.00,19.00,19.00,0.0,0.0,NaN,CokeJa01
81,80.0,Jack Fox,28.0,DET,P,17.0,0.0,NaN,1.0,1.0,...,NaN,0.0,0.0,0.00,17.00,17.00,0.0,0.0,PBAP-1,FoxxJa01
82,81.0,Josh Johnson,38.0,BAL,QB,6.0,0.0,NaN,2.0,3.0,...,15.3,1.0,5.0,25.00,3.00,3.00,0.0,0.0,NaN,JohnJo05
83,82.0,Stefon Diggs,31.0,HOU,WR,8.0,8.0,NaN,1.0,1.0,...,12.1,0.0,0.0,0.00,13.00,13.00,0.0,0.0,NaN,DiggSt00
84,83.0,Tyson Bagent,24.0,CHI,QB,4.0,0.0,NaN,2.0,2.0,...,47.6,0.0,0.0,0.00,5.50,5.50,0.0,0.0,NaN,BageTy00
85,84.0,Clayton Tune,25.0,ARI,QB,6.0,0.0,NaN,2.0,2.0,...,0.5,0.0,0.0,0.00,4.00,4.00,0.0,0.0,NaN,TuneCl00
86,85.0,Amon-Ra St. Brown,25.0,DET,WR,17.0,17.0,NaN,1.0,1.0,...,99.5,0.0,0.0,0.00,7.00,27.00,0.0,0.0,PBAP-1AP OPoY-11,StxxAm00
87,86.0,Kyle Trask,26.0,TAM,QB,4.0,0.0,NaN,1.0,1.0,...,88.0,0.0,0.0,0.00,5.00,5.00,0.0,0.0,NaN,TrasKy00
88,87.0,Bryan Anger,36.0,DAL,P,17.0,0.0,NaN,1.0,2.0,...,NaN,0.0,0.0,0.00,2.00,2.00,0.0,0.0,NaN,AngeBr00
89,88.0,Riley Dixon,31.0,DEN,P,17.0,0.0,NaN,1.0,1.0,...,NaN,0.0,0.0,0.00,3.00,3.00,0.0,0.0,NaN,DixoRi00
90,89.0,David Montgomery,27.0,DET,RB,14.0,14.0,NaN,1.0,1.0,...,100.0,0.0,0.0,0.00,3.00,23.00,0.0,0.0,NaN,MontDa01
91,90.0,JK Scott,29.0,LAC,P,17.0,0.0,NaN,1.0,1.0,...,NaN,0.0,0.0,0.00,3.00,3.00,0.0,0.0,NaN,ScotJK00
92,91.0,Keenan Allen,32.0,CHI,WR,15.0,15.0,NaN,0.0,1.0,...,0.0,0.0,0.0,0.00,0.00,-45.00,0.0,0.0,NaN,AlleKe00
93,92.0,Tutu Atwell,25.0,LAR,WR,17.0,5.0,NaN,0.0,1.0,...,1.5,0.0,0.0,0.00,0.00,0.00,0.0,0.0,NaN,AtweTu00
94,93.0,Saquon Barkley,27.0,PHI,RB,16.0,16.0,NaN,0.0,0.0,...,0.1,1.0,2.0,100.00,-2.00,-2.00,0.0,0.0,PBAP-1AP MVP-3AP OPoY-1AP CPoY-14,BarkSa00
95,94.0,Kendrick Bourne,29.0,NWE,WR,12.0,9.0,NaN,0.0,1.0,...,3.7,0.0,0.0,0.00,0.00,0.00,0.0,0.0,NaN,BourKe00
96,95.0,Tyler Boyd,30.0,TEN,WR,16.0,8.0,NaN,0.0,1.0,...,3.6,0.0,0.0,0.00,0.00,0.00,0.0,0.0,NaN,BoydTy00
97,96.0,Dyami Brown,25.0,WAS,WR,16.0,3.0,NaN,0.0,1.0,...,4.8,0.0,0.0,0.00,0.00,0.00,0.0,0.0,NaN,BrowDy00
98,97.0,Ty Chandler,26.0,MIN,RB,17.0,0.0,NaN,0.0,0.0,...,1.1,1.0,1.0,100.00,-1.00,-1.00,0.0,0.0,NaN,ChanTy01
99,98.0,Johnny Hekker,34.0,CAR,P,17.0,0.0,NaN,0.0,2.0,...,NaN,0.0,0.0,0.00,0.00,0.00,0.0,0.0,NaN,HekkJo00

In [414]:
vc_check =dfqb['Player'].value_counts()
multi_team_qb = vc_check[vc_check > 1].index
multi_team_qb
multi_team_qb_df = dfqb[dfqb['Player'].isin(multi_team_qb)]
multi_team_qb_df = multi_team_qb_df[multi_team_qb_df['Team'].str.contains('TM')]

In [415]:
single_team_qb_df = dfqb[~dfqb['Player'].isin(multi_team_qb)]
qb_dfs = [single_team_qb_df,multi_team_qb_df]
qb_df = pd.concat(qb_dfs)

In [416]:
dfqb.columns
keep_cols1 =['Player', 'Age', 'Team', 'Pos', 'G', 'Cmp', 'Att', 'Yds', 'TD', 'Int']
qb_df = qb_df[keep_cols1]    
qb_df = qb_df[qb_df['Pos'] == 'QB']
qb_df

,Player,Age,Team,Pos,G,Cmp,Att,Yds,TD,Int
0,Joe Burrow,28.0,CIN,QB,17.0,460.0,652.0,4918.0,43.0,9.0
1,Jared Goff,30.0,DET,QB,17.0,390.0,539.0,4629.0,37.0,12.0
2,Baker Mayfield,29.0,TAM,QB,17.0,407.0,570.0,4500.0,41.0,16.0
3,Geno Smith,34.0,SEA,QB,17.0,407.0,578.0,4320.0,21.0,15.0
4,Sam Darnold,27.0,MIN,QB,17.0,361.0,545.0,4319.0,35.0,12.0
5,Lamar Jackson,27.0,BAL,QB,17.0,316.0,474.0,4172.0,41.0,4.0
6,Patrick Mahomes,29.0,KAN,QB,16.0,392.0,581.0,3928.0,26.0,11.0
7,Aaron Rodgers,41.0,NYJ,QB,17.0,368.0,584.0,3897.0,28.0,11.0
8,Justin Herbert,26.0,LAC,QB,17.0,332.0,504.0,3870.0,23.0,3.0
9,Brock Purdy,25.0,SFO,QB,15.0,300.0,455.0,3864.0,20.0,12.0
10,Kyler Murray,27.0,ARI,QB,17.0,372.0,541.0,3851.0,21.0,11.0
11,Bo Nix,24.0,DEN,QB,17.0,376.0,567.0,3775.0,29.0,12.0
12,Matthew Stafford,36.0,LAR,QB,16.0,340.0,517.0,3762.0,20.0,8.0
13,Josh Allen,28.0,BUF,QB,17.0,307.0,483.0,3731.0,28.0,6.0
14,C.J. Stroud,23.0,HOU,QB,17.0,336.0,532.0,3727.0,20.0,12.0
15,Jayden Daniels,24.0,WAS,QB,17.0,331.0,480.0,3568.0,25.0,9.0
16,Caleb Williams,23.0,CHI,QB,17.0,351.0,562.0,3541.0,20.0,6.0
17,Kirk Cousins,36.0,ATL,QB,14.0,303.0,453.0,3508.0,18.0,16.0
18,Jordan Love,26.0,GNB,QB,15.0,268.0,425.0,3389.0,25.0,11.0
19,Jalen Hurts,26.0,PHI,QB,15.0,248.0,361.0,2903.0,18.0,5.0
20,Tua Tagovailoa,26.0,MIA,QB,11.0,291.0,399.0,2867.0,19.0,7.0
21,Russell Wilson,36.0,PIT,QB,11.0,214.0,336.0,2482.0,16.0,5.0
22,Bryce Young,23.0,CAR,QB,14.0,234.0,384.0,2403.0,15.0,9.0
23,Drake Maye,22.0,NWE,QB,13.0,225.0,338.0,2276.0,15.0,10.0
24,Derek Carr,33.0,NOR,QB,10.0,189.0,279.0,2145.0,15.0,5.0
25,Jameis Winston,30.0,CLE,QB,12.0,181.0,296.0,2121.0,13.0,12.0
26,Will Levis,25.0,TEN,QB,12.0,190.0,301.0,2091.0,13.0,12.0
27,Daniel Jones,27.0,NYG,QB,10.0,216.0,341.0,2070.0,8.0,7.0
28,Trevor Lawrence,25.0,JAX,QB,10.0,172.0,284.0,2045.0,11.0,7.0
29,Gardner Minshew II,28.0,LVR,QB,10.0,203.0,306.0,2013.0,9.0,10.0
30,Dak Prescott,31.0,DAL,QB,8.0,185.0,286.0,1978.0,11.0,8.0
31,Cooper Rush,31.0,DAL,QB,12.0,187.0,308.0,1844.0,12.0,5.0
32,Anthony Richardson,22.0,IND,QB,11.0,126.0,264.0,1814.0,8.0,12.0
33,Joe Flacco,39.0,IND,QB,8.0,162.0,248.0,1761.0,12.0,7.0
34,Mac Jones,26.0,JAX,QB,10.0,171.0,262.0,1672.0,8.0,8.0
35,Aidan O'Connell,26.0,LVR,QB,9.0,154.0,243.0,1612.0,8.0,4.0
36,Mason Rudolph,29.0,TEN,QB,8.0,146.0,228.0,1530.0,9.0,9.0
37,Spencer Rattler,24.0,NOR,QB,7.0,130.0,228.0,1317.0,4.0,5.0
38,Deshaun Watson,29.0,CLE,QB,7.0,137.0,216.0,1148.0,5.0,3.0
39,Justin Fields,25.0,PIT,QB,10.0,106.0,161.0,1106.0,5.0,1.0
40,Drew Lock,28.0,NYG,QB,8.0,107.0,181.0,1071.0,6.0,5.0
41,Andy Dalton,37.0,CAR,QB,6.0,106.0,160.0,989.0,7.0,6.0
42,Tyler Huntley,26.0,MIA,QB,5.0,86.0,133.0,829.0,3.0,3.0
43,Jacoby Brissett,32.0,NWE,QB,8.0,95.0,161.0,826.0,2.0,1.0
44,Michael Penix,24.0,ATL,QB,5.0,61.0,105.0,775.0,3.0,3.0
45,Malik Willis,25.0,GNB,QB,7.0,40.0,54.0,550.0,3.0,0.0
46,Desmond Ridder,25.0,LVR,QB,6.0,52.0,85.0,458.0,2.0,2.0
47,Dorian Thompson-Robinson,25.0,CLE,QB,7.0,61.0,118.0,440.0,0.0,6.0
48,Marcus Mariota,31.0,WAS,QB,3.0,34.0,44.0,364.0,4.0,0.0
49,Joshua Dobbs,29.0,SFO,QB,2.0,32.0,47.0,361.0,2.0,2.0
50,Jimmy Garoppolo,33.0,LAR,QB,1.0,27.0,41.0,334.0,2.0,1.0
51,Tanner McKee,24.0,PHI,QB,2.0,30.0,45.0,323.0,4.0,0.0
52,Kenny Pickett,26.0,PHI,QB,5.0,25.0,42.0,291.0,2.0,1.0
56,Trey Lance,24.0,DAL,QB,4.0,25.0,41.0,266.0,0.0,1.0
57,Tommy DeVito,26.0,NYG,QB,3.0,31.0,44.0,257.0,0.0,0.0
58,Joe Milton,24.0,NWE,QB,1.0,22.0,29.0,241.0,1.0,0.0
59,Jake Haener,25.0,NOR,QB,8.0,18.0,39.0,226.0,1.0,1.0
60,Davis Mills,26.0,HOU,QB,4.0,20.0,36.0,212.0,0.0,0.0
61,Brandon Allen,32.0,SFO,QB,3.0,17.0,30.0,199.0,1.0,2.0
62,Skylar Thompson,27.0,MIA,QB,3.0,21.0,33.0,187.0,0.0,0.0
63,Mitchell Trubisky,30.0,BUF,QB,9.0,19.0,26.0,179.0,2.0,0.0
64,Bailey Zappe,25.0,CLE,QB,1.0,16.0,31.0,170.0,1.0,2.0
65,Tyrod Taylor,35.0,NYJ,QB,2.0,17.0,22.0,119.0,3.0,0.0
66,Carson Wentz,32.0,KAN,QB,3.0,12.0,19.0,118.0,0.0,0.0
67,Hendon Hooker,26.0,DET,QB,3.0,6.0,9.0,62.0,0.0,0.0
68,Nick Mullens,29.0,MIN,QB,4.0,2.0,2.0,38.0,0.0,0.0
72,Taylor Heinicke,31.0,LAC,QB,4.0,3.0,5.0,28.0,0.0,0.0
73,Mike White,29.0,BUF,QB,1.0,3.0,11.0,28.0,0.0,0.0
74,Sam Howell,24.0,SEA,QB,2.0,5.0,14.0,24.0,0.0,1.0
79,Kyle Allen,28.0,PIT,QB,1.0,1.0,1.0,19.0,0.0,0.0
82,Josh Johnson,38.0,BAL,QB,6.0,2.0,3.0,17.0,0.0,0.0
84,Tyson Bagent,24.0,CHI,QB,4.0,2.0,2.0,11.0,0.0,0.0
85,Clayton Tune,25.0,ARI,QB,6.0,2.0,2.0,8.0,0.0,0.0
87,Kyle Trask,26.0,TAM,QB,4.0,1.0,1.0,5.0,0.0,0.0
107,Chris Oladokun,27.0,KAN,QB,1.0,0.0,0.0,0.0,0.0,0.0
53,Tim Boyle,30.0,2TM,QB,3.0,27.0,50.0,276.0,1.0,1.0

In [417]:
qb_df.columns = qb_df.columns.str.strip()
qb_scrimmage_df.columns = qb_scrimmage_df.columns.str.strip()
qb_scrimmage_correct = qb_scrimmage_df[['Player', 'Scrimmage YScm', 'Scrimmage RRTD']].copy()
qb_df = qb_df.merge(qb_scrimmage_correct, on='Player', how='left')


#qb_df['Pts'] = qb_df['Yds'].astype(float) / 25 + qb_df['TD'].astype(float) * 4 - qb_df['Int'].astype(float) * 2 + qb_df['Scrimmage YScm'].astype(float) / 10 + qb_df['Scrimmage RRTD'].astype(float) * 6
qb_df.columns

Index(['Player', 'Age', 'Team', 'Pos', 'G', 'Cmp', 'Att', 'Yds', 'TD', 'Int',
       'Scrimmage YScm', 'Scrimmage RRTD'],
      dtype='object')

In [418]:

keep_cols3= ['Player', 'Age', 'Team', 'Pos', 'G', 'Cmp', 'Att', 'Yds', 'TD', 'Int',
        'Scrimmage YScm', 'Scrimmage RRTD']
qb_df = qb_df[keep_cols3]
qb_df.head(50)

,Player,Age,Team,Pos,G,Cmp,Att,Yds,TD,Int,Scrimmage YScm,Scrimmage RRTD
0,Joe Burrow,28.0,CIN,QB,17.0,460.0,652.0,4918.0,43.0,9.0,201,2
1,Jared Goff,30.0,DET,QB,17.0,390.0,539.0,4629.0,37.0,12.0,63,1
2,Baker Mayfield,29.0,TAM,QB,17.0,407.0,570.0,4500.0,41.0,16.0,378,3
3,Geno Smith,34.0,SEA,QB,17.0,407.0,578.0,4320.0,21.0,15.0,272,2
4,Sam Darnold,27.0,MIN,QB,17.0,361.0,545.0,4319.0,35.0,12.0,212,1
5,Lamar Jackson,27.0,BAL,QB,17.0,316.0,474.0,4172.0,41.0,4.0,915,4
6,Patrick Mahomes,29.0,KAN,QB,16.0,392.0,581.0,3928.0,26.0,11.0,309,2
7,Aaron Rodgers,41.0,NYJ,QB,17.0,368.0,584.0,3897.0,28.0,11.0,107,0
8,Justin Herbert,26.0,LAC,QB,17.0,332.0,504.0,3870.0,23.0,3.0,306,2
9,Brock Purdy,25.0,SFO,QB,15.0,300.0,455.0,3864.0,20.0,12.0,323,5
10,Kyler Murray,27.0,ARI,QB,17.0,372.0,541.0,3851.0,21.0,11.0,572,5
11,Bo Nix,24.0,DEN,QB,17.0,376.0,567.0,3775.0,29.0,12.0,432,5
12,Matthew Stafford,36.0,LAR,QB,16.0,340.0,517.0,3762.0,20.0,8.0,41,0
13,Josh Allen,28.0,BUF,QB,17.0,307.0,483.0,3731.0,28.0,6.0,538,13
14,C.J. Stroud,23.0,HOU,QB,17.0,336.0,532.0,3727.0,20.0,12.0,233,0
15,Jayden Daniels,24.0,WAS,QB,17.0,331.0,480.0,3568.0,25.0,9.0,891,6
16,Caleb Williams,23.0,CHI,QB,17.0,351.0,562.0,3541.0,20.0,6.0,489,0
17,Kirk Cousins,36.0,ATL,QB,14.0,303.0,453.0,3508.0,18.0,16.0,0,0
18,Jordan Love,26.0,GNB,QB,15.0,268.0,425.0,3389.0,25.0,11.0,83,1
19,Jalen Hurts,26.0,PHI,QB,15.0,248.0,361.0,2903.0,18.0,5.0,630,14
20,Tua Tagovailoa,26.0,MIA,QB,11.0,291.0,399.0,2867.0,19.0,7.0,49,0
21,Russell Wilson,36.0,PIT,QB,11.0,214.0,336.0,2482.0,16.0,5.0,155,2
22,Bryce Young,23.0,CAR,QB,14.0,234.0,384.0,2403.0,15.0,9.0,249,6
23,Drake Maye,22.0,NWE,QB,13.0,225.0,338.0,2276.0,15.0,10.0,421,2
24,Derek Carr,33.0,NOR,QB,10.0,189.0,279.0,2145.0,15.0,5.0,71,1
25,Jameis Winston,30.0,CLE,QB,12.0,181.0,296.0,2121.0,13.0,12.0,83,1
26,Will Levis,25.0,TEN,QB,12.0,190.0,301.0,2091.0,13.0,12.0,183,0
27,Daniel Jones,27.0,NYG,QB,10.0,216.0,341.0,2070.0,8.0,7.0,265,2
28,Trevor Lawrence,25.0,JAX,QB,10.0,172.0,284.0,2045.0,11.0,7.0,114,3
29,Gardner Minshew II,28.0,LVR,QB,10.0,203.0,306.0,2013.0,9.0,10.0,58,0
30,Dak Prescott,31.0,DAL,QB,8.0,185.0,286.0,1978.0,11.0,8.0,54,1
31,Cooper Rush,31.0,DAL,QB,12.0,187.0,308.0,1844.0,12.0,5.0,18,0
32,Anthony Richardson,22.0,IND,QB,11.0,126.0,264.0,1814.0,8.0,12.0,498,6
33,Joe Flacco,39.0,IND,QB,8.0,162.0,248.0,1761.0,12.0,7.0,26,0
34,Mac Jones,26.0,JAX,QB,10.0,171.0,262.0,1672.0,8.0,8.0,92,1
35,Aidan O'Connell,26.0,LVR,QB,9.0,154.0,243.0,1612.0,8.0,4.0,30,1
36,Mason Rudolph,29.0,TEN,QB,8.0,146.0,228.0,1530.0,9.0,9.0,106,1
37,Spencer Rattler,24.0,NOR,QB,7.0,130.0,228.0,1317.0,4.0,5.0,146,0
38,Deshaun Watson,29.0,CLE,QB,7.0,137.0,216.0,1148.0,5.0,3.0,148,1
39,Justin Fields,25.0,PIT,QB,10.0,106.0,161.0,1106.0,5.0,1.0,289,5
40,Drew Lock,28.0,NYG,QB,8.0,107.0,181.0,1071.0,6.0,5.0,133,2
41,Andy Dalton,37.0,CAR,QB,6.0,106.0,160.0,989.0,7.0,6.0,34,0
42,Tyler Huntley,26.0,MIA,QB,5.0,86.0,133.0,829.0,3.0,3.0,135,2
43,Jacoby Brissett,32.0,NWE,QB,8.0,95.0,161.0,826.0,2.0,1.0,62,0
44,Michael Penix,24.0,ATL,QB,5.0,61.0,105.0,775.0,3.0,3.0,11,1
45,Malik Willis,25.0,GNB,QB,7.0,40.0,54.0,550.0,3.0,0.0,138,1
46,Desmond Ridder,25.0,LVR,QB,6.0,52.0,85.0,458.0,2.0,2.0,36,0
47,Dorian Thompson-Robinson,25.0,CLE,QB,7.0,61.0,118.0,440.0,0.0,6.0,122,0
48,Marcus Mariota,31.0,WAS,QB,3.0,34.0,44.0,364.0,4.0,0.0,92,1
49,Joshua Dobbs,29.0,SFO,QB,2.0,32.0,47.0,361.0,2.0,2.0,24,2

In [419]:
qb_df['Pts'] = qb_df['Yds'].astype(float) / 25 + qb_df['TD'].astype(float) * 4 - qb_df['Int'].astype(float) * 2 + qb_df['Scrimmage YScm'].astype(float) / 10 + qb_df['Scrimmage RRTD'].astype(float) * 6
qb_df.sort_values('Pts',ascending=False)

,Player,Age,Team,Pos,G,Cmp,Att,Yds,TD,Int,Scrimmage YScm,Scrimmage RRTD,Pts
5,Lamar Jackson,27.0,BAL,QB,17.0,316.0,474.0,4172.0,41.0,4.0,915,4,438.38
0,Joe Burrow,28.0,CIN,QB,17.0,460.0,652.0,4918.0,43.0,9.0,201,2,382.82
13,Josh Allen,28.0,BUF,QB,17.0,307.0,483.0,3731.0,28.0,6.0,538,13,381.04
2,Baker Mayfield,29.0,TAM,QB,17.0,407.0,570.0,4500.0,41.0,16.0,378,3,367.80
15,Jayden Daniels,24.0,WAS,QB,17.0,331.0,480.0,3568.0,25.0,9.0,891,6,349.82
19,Jalen Hurts,26.0,PHI,QB,15.0,248.0,361.0,2903.0,18.0,5.0,630,14,325.12
1,Jared Goff,30.0,DET,QB,17.0,390.0,539.0,4629.0,37.0,12.0,63,1,321.46
11,Bo Nix,24.0,DEN,QB,17.0,376.0,567.0,3775.0,29.0,12.0,432,5,316.20
4,Sam Darnold,27.0,MIN,QB,17.0,361.0,545.0,4319.0,35.0,12.0,212,1,315.96
10,Kyler Murray,27.0,ARI,QB,17.0,372.0,541.0,3851.0,21.0,11.0,572,5,303.24
8,Justin Herbert,26.0,LAC,QB,17.0,332.0,504.0,3870.0,23.0,3.0,306,2,283.40
6,Patrick Mahomes,29.0,KAN,QB,16.0,392.0,581.0,3928.0,26.0,11.0,309,2,282.02
9,Brock Purdy,25.0,SFO,QB,15.0,300.0,455.0,3864.0,20.0,12.0,323,5,272.86
3,Geno Smith,34.0,SEA,QB,17.0,407.0,578.0,4320.0,21.0,15.0,272,2,266.00
16,Caleb Williams,23.0,CHI,QB,17.0,351.0,562.0,3541.0,20.0,6.0,489,0,258.54
7,Aaron Rodgers,41.0,NYJ,QB,17.0,368.0,584.0,3897.0,28.0,11.0,107,0,256.58
14,C.J. Stroud,23.0,HOU,QB,17.0,336.0,532.0,3727.0,20.0,12.0,233,0,228.38
18,Jordan Love,26.0,GNB,QB,15.0,268.0,425.0,3389.0,25.0,11.0,83,1,227.86
12,Matthew Stafford,36.0,LAR,QB,16.0,340.0,517.0,3762.0,20.0,8.0,41,0,218.58
22,Bryce Young,23.0,CAR,QB,14.0,234.0,384.0,2403.0,15.0,9.0,249,6,199.02
23,Drake Maye,22.0,NWE,QB,13.0,225.0,338.0,2276.0,15.0,10.0,421,2,185.14
20,Tua Tagovailoa,26.0,MIA,QB,11.0,291.0,399.0,2867.0,19.0,7.0,49,0,181.58
21,Russell Wilson,36.0,PIT,QB,11.0,214.0,336.0,2482.0,16.0,5.0,155,2,180.78
17,Kirk Cousins,36.0,ATL,QB,14.0,303.0,453.0,3508.0,18.0,16.0,0,0,180.32
32,Anthony Richardson,22.0,IND,QB,11.0,126.0,264.0,1814.0,8.0,12.0,498,6,166.36
24,Derek Carr,33.0,NOR,QB,10.0,189.0,279.0,2145.0,15.0,5.0,71,1,148.90
28,Trevor Lawrence,25.0,JAX,QB,10.0,172.0,284.0,2045.0,11.0,7.0,114,3,141.20
27,Daniel Jones,27.0,NYG,QB,10.0,216.0,341.0,2070.0,8.0,7.0,265,2,139.30
26,Will Levis,25.0,TEN,QB,12.0,190.0,301.0,2091.0,13.0,12.0,183,0,129.94
25,Jameis Winston,30.0,CLE,QB,12.0,181.0,296.0,2121.0,13.0,12.0,83,1,127.14
39,Justin Fields,25.0,PIT,QB,10.0,106.0,161.0,1106.0,5.0,1.0,289,5,121.14
30,Dak Prescott,31.0,DAL,QB,8.0,185.0,286.0,1978.0,11.0,8.0,54,1,118.52
31,Cooper Rush,31.0,DAL,QB,12.0,187.0,308.0,1844.0,12.0,5.0,18,0,113.56
33,Joe Flacco,39.0,IND,QB,8.0,162.0,248.0,1761.0,12.0,7.0,26,0,107.04
29,Gardner Minshew II,28.0,LVR,QB,10.0,203.0,306.0,2013.0,9.0,10.0,58,0,102.32
34,Mac Jones,26.0,JAX,QB,10.0,171.0,262.0,1672.0,8.0,8.0,92,1,98.08
35,Aidan O'Connell,26.0,LVR,QB,9.0,154.0,243.0,1612.0,8.0,4.0,30,1,97.48
36,Mason Rudolph,29.0,TEN,QB,8.0,146.0,228.0,1530.0,9.0,9.0,106,1,95.80
40,Drew Lock,28.0,NYG,QB,8.0,107.0,181.0,1071.0,6.0,5.0,133,2,82.14
38,Deshaun Watson,29.0,CLE,QB,7.0,137.0,216.0,1148.0,5.0,3.0,148,1,80.72
37,Spencer Rattler,24.0,NOR,QB,7.0,130.0,228.0,1317.0,4.0,5.0,146,0,73.28
42,Tyler Huntley,26.0,MIA,QB,5.0,86.0,133.0,829.0,3.0,3.0,135,2,64.66
41,Andy Dalton,37.0,CAR,QB,6.0,106.0,160.0,989.0,7.0,6.0,34,0,58.96
45,Malik Willis,25.0,GNB,QB,7.0,40.0,54.0,550.0,3.0,0.0,138,1,53.80
48,Marcus Mariota,31.0,WAS,QB,3.0,34.0,44.0,364.0,4.0,0.0,92,1,45.76
43,Jacoby Brissett,32.0,NWE,QB,8.0,95.0,161.0,826.0,2.0,1.0,62,0,45.24
44,Michael Penix,24.0,ATL,QB,5.0,61.0,105.0,775.0,3.0,3.0,11,1,44.10
49,Joshua Dobbs,29.0,SFO,QB,2.0,32.0,47.0,361.0,2.0,2.0,24,2,32.84
51,Tanner McKee,24.0,PHI,QB,2.0,30.0,45.0,323.0,4.0,0.0,-1,0,28.82
46,Desmond Ridder,25.0,LVR,QB,6.0,52.0,85.0,458.0,2.0,2.0,36,0,25.92
52,Kenny Pickett,26.0,PHI,QB,5.0,25.0,42.0,291.0,2.0,1.0,15,1,25.14
55,Joe Milton,24.0,NWE,QB,1.0,22.0,29.0,241.0,1.0,0.0,16,1,21.24
50,Jimmy Garoppolo,33.0,LAR,QB,1.0,27.0,41.0,334.0,2.0,1.0,5,0,19.86
62,Tyrod Taylor,35.0,NYJ,QB,2.0,17.0,22.0,119.0,3.0,0.0,13,0,18.06
47,Dorian Thompson-Robinson,25.0,CLE,QB,7.0,61.0,118.0,440.0,0.0,6.0,122,0,17.80
60,Mitchell Trubisky,30.0,BUF,QB,9.0,19.0,26.0,179.0,2.0,0.0,1,0,15.26
75,Tim Boyle,30.0,2TM,QB,3.0,27.0,50.0,276.0,1.0,1.0,9,0,13.94
54,Tommy DeVito,26.0,NYG,QB,3.0,31.0,44.0,257.0,0.0,0.0,32,0,13.48
56,Jake Haener,25.0,NOR,QB,8.0,18.0,39.0,226.0,1.0,1.0,22,0,13.24
53,Trey Lance,24.0,DAL,QB,4.0,25.0,41.0,266.0,0.0,1.0,41,0,12.74
57,Davis Mills,26.0,HOU,QB,4.0,20.0,36.0,212.0,0.0,0.0,11,0,9.58
58,Brandon Allen,32.0,SFO,QB,3.0,17.0,30.0,199.0,1.0,2.0,4,0,8.36
59,Skylar Thompson,27.0,MIA,QB,3.0,21.0,33.0,187.0,0.0,0.0,4,0,7.88
61,Bailey Zappe,25.0,CLE,QB,1.0,16.0,31.0,170.0,1.0,2.0,2,0,7.00
63,Carson Wentz,32.0,KAN,QB,3.0,12.0,19.0,118.0,0.0,0.0,0,0,4.72
66,Taylor Heinicke,31.0,LAC,QB,4.0,3.0,5.0,28.0,0.0,0.0,20,0,3.12
64,Hendon Hooker,26.0,DET,QB,3.0,6.0,9.0,62.0,0.0,0.0,2,0,2.68
65,Nick Mullens,29.0,MIN,QB,4.0,2.0,2.0,38.0,0.0,0.0,-2,0,1.32
70,Josh Johnson,38.0,BAL,QB,6.0,2.0,3.0,17.0,0.0,0.0,1,0,0.78
74,Chris Oladokun,27.0,KAN,QB,1.0,0.0,0.0,0.0,0.0,0.0,5,0,0.50
72,Clayton Tune,25.0,ARI,QB,6.0,2.0,2.0,8.0,0.0,0.0,-4,0,-0.08
73,Kyle Trask,26.0,TAM,QB,4.0,1.0,1.0,5.0,0.0,0.0,-4,0,-0.20
71,Tyson Bagent,24.0,CHI,QB,4.0,2.0,2.0,11.0,0.0,0.0,-7,0,-0.26
68,Sam Howell,24.0,SEA,QB,2.0,5.0,14.0,24.0,0.0,1.0,2,0,-0.84
67,Mike White,29.0,BUF,QB,1.0,3.0,11.0,28.0,0.0,0.0,NaN,NaN,NaN
69,Kyle Allen,28.0,PIT,QB,1.0,1.0,1.0,19.0,0.0,0.0,NaN,NaN,NaN

In [ ]:
# Combine QB and player fantasy points
player_df.columns = player_df.columns.str.strip()
qb_pts_df = qb_df[['Player','Age','Team','Pos','G','Pts']]
player_pts_df = player_df[['Player','Age','Team','Pos','G','Pts']]

final_df = pd.concat([qb_pts_df, player_pts_df], ignore_index=True)

# Replace NaN fantasy points with 0
final_df['Pts'] = final_df['Pts'].fillna(0)
final_df['Age']= final_df['Age'].astype(int)
final_df['G']= final_df['G'].astype(int)

# Sort by fantasy points (highest first) and reset index
final_df = final_df.sort_values('Pts', ascending=False).reset_index(drop=True)

print(final_df.head(100))  # Top 100 players

                 Player  Age Team Pos   G     Pts
0         Lamar Jackson   27  BAL  QB  17  438.38
1         Ja'Marr Chase   24  CIN  WR  17  403.00
2            Joe Burrow   28  CIN  QB  17  382.82
3            Josh Allen   28  BUF  QB  17  381.04
4        Baker Mayfield   29  TAM  QB  17  367.80
5          Jahmyr Gibbs   22  DET  RB  17  364.90
6        Saquon Barkley   27  PHI  RB  16  351.30
7        Jayden Daniels   24  WAS  QB  17  349.82
8        Bijan Robinson   22  ATL  RB  17  339.70
9         Derrick Henry   30  BAL  RB  17  338.40
10          Jalen Hurts   26  PHI  QB  15  325.12
11           Jared Goff   30  DET  QB  17  321.46
12     Justin Jefferson   25  MIN  WR  17  316.60
13               Bo Nix   24  DEN  QB  17  316.20
14          Sam Darnold   27  MIN  QB  17  315.96
15    Amon-Ra St. Brown   25  DET  WR  17  313.90
16         Kyler Murray   27  ARI  QB  17  303.24
17        De'Von Achane   23  MIA  RB  17  299.90
18          Josh Jacobs   26  GNB  RB  17  299.10
19       Justin Herbert   26  LAC  QB  17  283.40
20      Patrick Mahomes   29  KAN  QB  16  282.02
21         Drake London   23  ATL  WR  17  280.80
22         Brian Thomas   22  JAX  WR  17  280.00
23       Kyren Williams   24  LAR  RB  16  278.10
24          Brock Purdy   25  SFO  QB  15  272.86
25         Malik Nabers   21  NYG  WR  15  271.60
26       Terry McLaurin   29  WAS  WR  17  269.80
27           James Cook   25  BUF  RB  16  266.70
28           Geno Smith   34  SEA  QB  17  266.00
29         Alvin Kamara   29  NOR  RB  14  265.30
30          CeeDee Lamb   25  DAL  WR  15  263.40
31         Brock Bowers   22  LVR  TE  17  262.70
32       Caleb Williams   23  CHI  QB  17  258.54
33        Aaron Rodgers   41  NYJ  QB  17  256.58
34          Chase Brown   24  CIN  RB  16  255.00
35       Garrett Wilson   24  NYJ  WR  17  253.90
36         James Conner   29  ARI  RB  16  251.80
37   Jaxon Smith-Njigba   22  SEA  WR  17  251.60
38          Aaron Jones   30  MIN  RB  17  247.60
39      Jonathan Taylor   25  IND  RB  14  246.70
40         Bucky Irving   22  TAM  RB  17  246.40
41        Chuba Hubbard   25  CAR  RB  15  245.60
42         Trey McBride   25  ARI  TE  16  243.80
43          Breece Hall   23  NYJ  RB  16  240.90
44            Joe Mixon   28  HOU  RB  14  240.50
45           Mike Evans   31  TAM  WR  14  240.40
46        Davante Adams   32  2TM  WR  14  239.30
47        Ladd McConkey   23  LAC  WR  16  238.90
48           D.J. Moore   27  CHI  WR  17  238.10
49     Courtland Sutton   29  DEN  WR  17  237.10
50          Jerry Jeudy   25  CLE  WR  17  236.90
51        George Kittle   31  SFO  TE  15  236.60
52          C.J. Stroud   23  HOU  QB  17  228.38
53          Jordan Love   26  GNB  QB  15  227.86
54          Jonnu Smith   29  MIA  TE  17  224.30
55          Tee Higgins   25  CIN  WR  12  224.10
56     David Montgomery   27  DET  RB  14  219.60
57     Matthew Stafford   36  LAR  QB  16  218.58
58          Tyreek Hill   30  MIA  WR  17  218.20
59           A.J. Brown   27  PHI  WR  13  216.90
60        Jakobi Meyers   28  LVR  WR  15  216.00
61       Jordan Addison   22  MIN  WR  15  212.50
62        D'Andre Swift   25  CHI  RB  17  212.50
63     Jameson Williams   23  DET  WR  15  212.20
64         Nico Collins   25  HOU  WR  12  210.60
65       Jauan Jennings   27  SFO  WR  15  210.50
66          Zay Flowers   24  BAL  WR  17  209.50
67           Puka Nacua   23  LAR  WR  11  206.60
68        Rachaad White   25  TAM  RB  16  205.60
69         Najee Harris   26  PIT  RB  17  204.60
70         Tony Pollard   27  TEN  RB  16  202.70
71          Rico Dowdle   26  DAL  RB  16  201.80
72        Calvin Ridley   30  TEN  WR  17  201.20
73        DeVonta Smith   26  PHI  WR  13  199.40
74          Bryce Young   23  CAR  QB  14  199.02
75          Jayden Reed   24  GNB  WR  17  199.00
76  Marvin Harrison Jr.   22  ARI  WR  17  198.50
77         Travis Kelce   35  KAN  TE  16  197.40
78         D.K. Metcalf   27  SEA  WR  15  195.20
79       Darnell Mooney   27  ATL  WR  16  193.20
80         J.K. Dobbins   26  LAC  RB  13  191.80
81         Mark Andrews   29  BAL  TE  17  188.80
82        Xavier Worthy   21  KAN  WR  17  187.20
83      Zach Charbonnet   23  SEA  RB  17  186.90
84         Keenan Allen   32  CHI  WR  15  186.40
85     Tyrone Tracy Jr.   25  NYG  RB  17  186.30
86           Drake Maye   22  NWE  QB  13  185.14
87           Josh Downs   23  IND  WR  14  183.50
88    Wan'Dale Robinson   23  NYG  WR  17  182.70
89        Khalil Shakir   24  BUF  WR  15  182.50
90       Tua Tagovailoa   26  MIA  QB  11  181.58
91   Kenneth Walker III   24  SEA  RB  11  181.20
92       Russell Wilson   36  PIT  QB  11  180.78
93         Kirk Cousins   36  ATL  QB  14  180.32
94  Rhamondre Stevenson   26  NWE  RB  15  177.90
95          Cooper Kupp   31  LAR  WR  12  175.00
96     Quentin Johnston   23  LAC  WR  15  174.70
97          Sam LaPorta   23  DET  TE  16  174.60
98       Rashod Bateman   25  BAL  WR  17  174.60
99            Zach Ertz   34  WAS  TE  17  173.40